name: Auto-Merge Pull Request
description: >
  Automatically merge pull requests once they are approved and
  required status checks are passing.
author: reitermarkus
branding:
  icon: git-pull-request
  color: purple

inputs:
  token:
    required: true
    description: >
      A GitHub Token other than the default `GITHUB_TOKEN` needs to be specified in order to be able to trigger other workflows.
    default: ${{ github.token }}
  merge-method:
    required: false
    description: >
      Specify which merge method to use. By default, will select the first one
      available in this order: `merge`, `squash`, `rebase`
  squash-title:
    required: false
    description: >
      (deprecated) Use the pull request title as the commit message when squashing. Prefer setting squash-commit-title and squash-commit-message.
    default: false
  squash-commit-title:
    required: false
    description: >
      Set the squash commit title to the supplied string. Available template variables include ${pull_request.title} and ${pull_request.number}.
  squash-commit-message:
    required: false
    description: >
      Set the squash commit body to the supplied string. Available template variables include ${pull_request.body}.
  do-not-merge-labels:
    required: false
    description: >
      When any of the labels in this comma-separated list is applied to a pull request, it will not be merged automatically.
  required-labels:
    required: false
    description: >
      Comma-separated list of labels that are required to be applied to a pull request for it to be merged automatically.
  pull-request:
    required: false
    description: >
      Try merging the specified pull request automatically. For example, you can pass an input from a `workflow_dispatch` event.
  pull-request-author-associations:
    required: false
    description: >
      Comma-separated list of required author associations for the pull request author.
      (By default, pull requests by any author are allowed.)
  review-author-associations:
    required: false
    default: OWNER,MEMBER,COLLABORATOR
    description: >
      Comma-separated list of required author associations for the review author.
      (By default, pull requests reviewed by `OWNER`s, `MEMBER`s and `COLLABORATOR`s are allowed.)
  dry-run:
    required: true
    description: >
      If set to `true`, will not actually merge pull requests but still perform all other checks.
    default: false

runs:
  using: 'node16'
  main: 'dist/index.js'
