name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'

inputs:
  token:
    required: true
    description: GitHub token
    default: ${{ github.token }}
  do-not-merge-labels:
    required: false
    description: >
      When any of these labels is applied to a pull request, do not automatically merge it.
  pull-request:
    required: false
    description: >
      Pull request which should be tried to be merged automatically.
  dry-run:
    required: true
    description: >
      If set to `true`, will not actually merge pull requests but still perform all other checks.
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
