name: Auto-Merge Pull Request
description: >
  Automatically merge pull requests once they are approved and
  required status checks are passing.
author: reitermarkus
branding:
  icon: git-pull-request
  color: purple

inputs:
  token:
    required: true
    description: >
      A GitHub Token other than the default `GITHUB_TOKEN` needs to be specified in order to be able to trigger other workflows.
    default: ${{ github.token }}
  merge-method:
    required: false
    description: >
      Specify which merge method to use. By default, will select the first one
      available in this order: `merge`, `squash`, `rebase`
  squash-title:
    required: false
    description: >
      Use the pull request title as the commit message when squashing.
    default: false
  do-not-merge-labels:
    required: false
    description: >
      When any of the labels in this comma-separated list is applied to a pull request, it will not be merged automatically.
  pull-request:
    required: false
    description: >
      Try merging the specified pull request automatically. For example, you can pass an input from a `workflow_dispatch` event.
  dry-run:
    required: true
    description: >
      If set to `true`, will not actually merge pull requests but still perform all other checks.
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'
