name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'

inputs:
  token:
    required: true
    description: GitHub token
    default: ${{ github.token }}
  minimum-approvals:
    required: true
    description: >
      Minimum number of approvals required for a pull request
      to be merged automatically.
    default: 1
  do-not-merge-labels:
    required: false
    description: >
      When any of these labels is applied to a pull request,
      do not automatically merge it.
  pull-request:
    required: false
    description: >
      Pull request which should be tried to be merged
      automatically.

runs:
  using: 'node12'
  main: 'dist/index.js'
